version: "3"

services:

  database:
    image: postgres
    ports:
      - "5432:5432"
    
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  vault:
    image: vault
    ports:
      - "8200:8200"
    # Referenced from https://raw.githubusercontent.com/mittwald/vaulTS/master/docker-compose.yaml
    command: [
        "sh",
        "-c",
        "(while ! nc -z 127.0.0.1 8200; \
        do \
        sleep 1; \
        echo 'waiting for vault service ...'; \
        done; \
        vault secrets enable totp \
        ) & vault server -dev",
      ]
    environment:
      VAULT_TOKEN: "dev-only-token"
      VAULT_DEV_ROOT_TOKEN_ID: "dev-only-token"

      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_DEV_LISTEN_ADDRESS: "127.0.0.1:8200"
