CREATE DATABASE test1;
CREATE DATABASE test2;
CREATE DATABASE test3;
GRANT ALL PRIVILEGES ON DATABASE test1 TO test;
GRANT ALL PRIVILEGES ON DATABASE test2 TO test;
GRANT ALL PRIVILEGES ON DATABASE test3 TO test;
