# Generated by Django 4.1 on 2022-09-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infections', '0002_alter_notifications_infection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='id',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='infection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infections.infectionhistory'),
        ),
    ]
